version: '3'
services:
  websocketClientOne:
    container_name: websocketClientOne
    build:
      context: ./websocket-client
      dockerfile: Dockerfile
    image: nginx
    ports:
      - "90:80"
    volumes:
      - ./websocket-client/build:/usr/share/nginx/html
  websocketClientTwo:
    container_name: websocketClientTwo
    build:
      context: ./websocket-client
      dockerfile: Dockerfile
    image: nginx
    ports:
      - "91:80"
    volumes:
      - ./websocket-client/build:/usr/share/nginx/html
  loadBalancer:
    image: nginx
    container_name: loadBalancer
    volumes:
      - ./loadbalancer.nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"